version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ic19
      POSTGRES_USER: ic19
      POSTGRES_PASSWORD: ic19
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ic19 -d ic19"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"

volumes:
  dbdata:
